### ISSUE TITLE
Error processing checkout. Please try again.

### ISSUE THREAD

**Issue by ahnaf0002** [cyberwombat/woocommerce-fastspring-payment-gateway#20]
When i am going to order from our web its showing me Error processing checkout. Please try again.
https://amadercode.com/premium-products/wp-amazon-shop-dropshipping-affiliate-plugin-details/

How to resolve this issue can you please give me a suggestion. Your help will cordially appreciable.

Thanks!!

**Comment by cyberwombat** [comment]
Thats a pretty generic Woo error. I would ensure that you are trying in test mode first and have debug on for the plugin which will make a log available under WooCommerce > Status > Logs. This may give you more info as to why it's failing the checkout.  My guess is that something is either incorrect with your FS keys/url or that you are not approved for live - I see that the site is on live mode so that could be it. Try test first with the correct test credentials/test credit card etc. Make sure to go through the [wiki](https://github.com/cyberwombat/woocommerce-fastspring-payment-gateway/wiki)
