### ISSUE TITLE
Storefront popup opens and close immediately.

### ISSUE THREAD

**Issue by Manika0205** [cyberwombat/woocommerce-fastspring-payment-gateway#32]
![Capture](https://user-images.githubusercontent.com/46884917/154410114-341c09ac-ad0f-477c-b629-d4b319682816.PNG)
 
I am getting 400 variation-not-found error when I click on the checkout button through my application.
I have whitelisted my local host URL, also checked the access token still getting this error.

**Comment by cyberwombat** [comment]
Hmm that's not an error I've ever encountered. The plugin creates the products on the fly so this is odd - it seems to indicate there is a product matching on FS - do you have products created within FS perhaps? If so you will want to remove them - or at least use a different SKU so they are not found.

**Comment by Manika0205** [comment]
I have checked that, there is no product created within FS.

**Comment by cyberwombat** [comment]
Hmm then I don't really have an idea. Am happy to look at your site to see if I see errors - sometimes there is a conflict with any FS snippet added but I have not encountered this message before - could be worth asking FS support what it actually means since there are no products. Ensure when testing that there is only the bare minimum of plugins - especially Woo addons - the term `variations` seems to indicate something product related so if FS has none perhaps your Woo setup is doing something unexpected.

**Comment by jaglah6** [comment]
same issue with my website [](https://toolstoon.com) Storefront popup opens and close immediately. it's working fine on subscription product but not open on simple products and i add free trial to subscription product it does not work. please help i need to fix this issue i want to provide free trial to customers but can't because of this issue

**Comment by jaglah6** [comment]
same issue with my website [https://toolstoon.com](https://toolstoon.com) Storefront popup opens and close immediately. it's working fine on subscription product but not open on simple products and i add free trial to subscription product it does not work. please help i need to fix this issue i want to provide free trial to customers but can't because of this issue

**Comment by cyberwombat** [comment]
Im sorry but I no longer maintain this plugin. It may be an issue with a version of Woo/subscriptions that are newer than those used when plugin was developed. It could be worth hiring someone on Upwork to test.debug and I'm happy to accept pull requests.

**Comment by jaglah6** [comment]
I get this error in my log file can you tell me what is it?
2023-03-20T16:27:28+00:00 CRITICAL Uncaught TypeError: Cannot access offset of type string on string in /var/www/vhosts/toolstoon.com/httpdocs/wp-content/plugins/woocommerce-fastspring-payment-gateway-master/includes/class-wc-gateway-fastspring-builder.php:92
Stack trace:
#0 /var/www/vhosts/toolstoon.com/httpdocs/wp-content/plugins/woocommerce-fastspring-payment-gateway-master/includes/class-wc-gateway-fastspring-builder.php(256): WC_Gateway_FastSpring_Builder::get_cart_items()
#1 /var/www/vhosts/toolstoon.com/httpdocs/wp-content/plugins/woocommerce-fastspring-payment-gateway-master/includes/class-wc-gateway-fastspring-builder.php(268): WC_Gateway_FastSpring_Builder::get_json_payload()
#2 /var/www/vhosts/toolstoon.com/httpdocs/wp-content/plugins/woocommerce-fastspring-payment-gateway-master/includes/class-wc-gateway-fastspring.php(261): WC_Gateway_FastSpring_Builder::get_secure_json_payload()
#3 /var/www/vhosts/toolstoon.com/httpdocs/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1050): WC_Gateway_FastSpring->process_payment()
#4 /var/www/vhosts/toolstoon.com/httpdocs/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1279): WC_Checkout->process_order_payment()
#5 /var/www/vhosts/toolstoon.com/httpdocs/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(481): WC_Checkout->process_checkout()
#6 /var/www/vhosts/toolstoon.com/httpdocs/wp-includes/class-wp-hook.php(308): WC_AJAX::checkout()
#7 /var/www/vhosts/toolstoon.com/httpdocs/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#8 /var/www/vhosts/toolstoon.com/httpdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#9 /var/www/vhosts/toolstoon.com/httpdocs/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(94): do_action()
#10 /var/www/vhosts/toolstoon.com/httpdocs/wp-includes/class-wp-hook.php(308): WC_AJAX::do_wc_ajax()
#11 /var/www/vhosts/toolstoon.com/httpdocs/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#12 /var/www/vhosts/toolstoon.com/httpdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#13 /var/www/vhosts/toolstoon.com/httpdocs/wp-includes/template-loader.php(13): do_action()
#14 /var/www/vhosts/toolstoon.com/httpdocs/wp-blog-header.php(19): require_once('...')
#15 /var/www/vhosts/toolstoon.com/httpdocs/index.php(17): require('...')
#16 {main}
  thrown in /var/www/vhosts/toolstoon.com/httpdocs/wp-content/plugins/woocommerce-fastspring-payment-gateway-master/includes/class-wc-gateway-fastspring-builder.php on line 92

**Comment by cyberwombat** [comment]
Most likely a code incompatibly error. This plugin was made for much earlier versions of WP/Woo. I know its running on WP 5.3.5 and Woo 3.5.0 (no subscriptions so can't tell you for that).  As mentioned in readme - this plugin is not maintained and quite outdated and will most likely not work unless you use old core/plugin versions.   Best approach is to hire someone on something like Upwork - a PHP developer familiar with WP/WooCommerce etc and have them update this plugin. Sorry I can't be more help but I no longer work at all with php/WP.
